[package]
name = "oxisynth"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "^1.2"

unoxidized={path="./unoxidized"}
soundfont-rs={path="./soundfont-rs"}

[dev-dependencies]
env_logger = "0.8.3"

[[example]]
name="sf2"
[[example]]
name="simple"