[package]
name = "oxidized-fluid"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "^1.2"
env_logger = "0.8.3"
nom = "6.1.2"
riff = "1.0.1"

unoxidized={path="./unoxidized"}
sf2={path="./sf2"}

[[examples]]
name="sf2"

